name: Build docker image

on:
  workflow_call:
    inputs:
      environment-name:
        type: string
      dockerfile_path:
        type: string
        default: '.deploy/Dockerfile'
      image_name:
        type: string
        default: 'ghcr.io/${GITHUB_REPOSITORY}:${CI_COMMIT_REF_SHORT}'
      registry_user:
        required: true
        type: string

jobs:
  build_docker_image:
    name: Build & deploy docker image
    environment:
      name: ${{ inputs.environment-name }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ inputs.registry_user }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up environment variables
        run: |
          export CI_COMMIT_REF_SHORT=${GITHUB_REF##*/}
          export CI_COMMIT_REF_SLUG=${CI_COMMIT_REF_SHORT//./_}
          echo "CI_COMMIT_REF_SLUG=${CI_COMMIT_REF_SLUG}" >> $GITHUB_ENV
          export CI_PROJECT_NAME=${GITHUB_REPOSITORY##*/}
          echo "CI_PROJECT_NAME=${CI_PROJECT_NAME//_/-}" >> $GITHUB_ENV
          echo "CI_REGISTRY_IMAGE=${{ inputs.image_name }}" >> $GITHUB_ENV

      - name: Build image and publish to package repository
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ inputs.image_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ${{ inputs.dockerfile_path }}